# Generated by Django 3.2.25 on 2026-03-16 20:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='modifiers',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='change_returned',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_response',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tendered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
