# Generated by Django 3.2.25 on 2026-03-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_created_by_alter_category_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergen_tags',
            field=models.TextField(default='[]'),
        ),
    ]
