# Generated by Django 6.0.3 on 2026-03-25 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_outletproductstatus_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Products without a category will appear as 'Uncategorized'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='menu.category'),
        ),
    ]
