# Generated by Django 6.0.3 on 2026-03-25 23:13

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_make_category_nullable_in_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIImageGenerationBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('monthly_budget', models.DecimalField(decimal_places=2, help_text='Monthly budget limit in INR', max_digits=10)),
                ('alert_threshold', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Alert when % of budget is reached (default: 80%)', max_digits=5)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total spent this month in INR', max_digits=10)),
                ('total_images', models.IntegerField(default=0, help_text='Total images generated this month')),
                ('alert_sent', models.BooleanField(default=False, help_text='Whether alert email was sent')),
                ('budget_exceeded', models.BooleanField(default=False, help_text='Whether budget has been exceeded')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Image Generation Budget',
                'verbose_name_plural': 'AI Image Generation Budgets',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AIImageGenerationCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('together', 'Together AI'), ('huggingface', 'Hugging Face'), ('openrouter', 'OpenRouter')], default='together', max_length=20)),
                ('model_name', models.CharField(help_text='AI model used (e.g., FLUX.1-schnell)', max_length=100)),
                ('prompt', models.TextField(help_text='Prompt used for generation')),
                ('image_url', models.URLField(blank=True, help_text='URL of generated image', null=True)),
                ('image_path', models.CharField(blank=True, help_text='Local file path', max_length=500, null=True)),
                ('image_size', models.CharField(default='1024x1024', help_text='Image dimensions', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('retry', 'Retry')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if generation failed', null=True)),
                ('cost_per_image', models.DecimalField(decimal_places=2, default=Decimal('1.15'), help_text='Cost per image in INR (₹1.15 default)', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('1.15'), help_text='Total cost for this generation in INR', max_digits=10)),
                ('generation_time_seconds', models.DecimalField(blank=True, decimal_places=2, help_text='Time taken to generate image in seconds', max_digits=10, null=True)),
                ('request_metadata', models.TextField(default='{}', help_text='JSON metadata about the request')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Product for which image was generated', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_image_costs', to='menu.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Image Generation Cost',
                'verbose_name_plural': 'AI Image Generation Costs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='menu_aiimag_created_1d05f7_idx'), models.Index(fields=['provider'], name='menu_aiimag_provide_279275_idx'), models.Index(fields=['status'], name='menu_aiimag_status_5a5852_idx'), models.Index(fields=['product'], name='menu_aiimag_product_4bbed0_idx')],
            },
        ),
    ]
