# Generated by Django 3.2.25 on 2026-03-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('owner', 'Owner'), ('area_manager', 'Area Manager'), ('outlet_manager', 'Outlet Manager'), ('cashier', 'Cashier'), ('kitchen', 'Kitchen Staff'), ('inventory_manager', 'Inventory Manager'), ('delivery_manager', 'Delivery Manager'), ('distributor', 'Distributor')], default='cashier', max_length=50),
        ),
    ]
