# Generated by Django 3.2.25 on 2026-04-19 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0007_outlet_client'),
        ('accounts', '0004_client_user_is_email_verified_user_last_login_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTerminalKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='e.g. "Counter 1"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_keys', to='outlets.outlet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
