# Generated by Django 3.2.25 on 2026-03-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0002_alter_outlet_created_by_alter_outlet_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='operating_hours',
            field=models.TextField(default='{}'),
        ),
    ]
