# Generated by Django 3.2.25 on 2026-03-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0003_alter_outlet_operating_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='base_tax_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='outlet',
            name='receipt_footer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='receipt_header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
