# Generated by Django 3.2.25 on 2026-03-19 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0004_auto_20260318_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum outstanding credit allowed for this distributor.', max_digits=12),
        ),
        migrations.AddField(
            model_name='outlet',
            name='distributor_discount_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage discount off MRP granted to this distributor.', max_digits=5),
        ),
        migrations.AddField(
            model_name='outlet',
            name='outlet_type',
            field=models.CharField(choices=[('main', 'Main Branch (HQ)'), ('retail', 'Retail Outlet'), ('distributor', 'Distributor'), ('kiosk', 'Kiosk')], default='retail', max_length=20),
        ),
        migrations.AddField(
            model_name='outlet',
            name='parent_outlet',
            field=models.ForeignKey(blank=True, help_text='For distributors: points to the main branch that supplies them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_outlets', to='outlets.outlet'),
        ),
    ]
