# Generated by Django 3.2.25 on 2026-03-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0005_auto_20260319_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='branch_type',
            field=models.CharField(blank=True, choices=[('own', 'Own Branch'), ('franchise', 'Franchise Branch')], help_text='For distributors: own branch or franchise branch.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this outlet is currently active.'),
        ),
    ]
