# Generated by Django 6.0.3 on 2026-03-26 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_client_user_is_email_verified_user_last_login_ip_and_more'),
        ('outlets', '0006_outlet_branch_type_and_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this outlet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='accounts.client'),
        ),
    ]
